name: Run GitHub App Manually

on:
  workflow_dispatch:
    

jobs:
  run-app:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev
        working-directory: githubapp

      - name: Write private key to file
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > githubapp/private-key.pem
          chmod 600 githubapp/private-key.pem

      - name: Run the GitHub App
        run: pipenv run python app.py
        working-directory: githubapp
