name: GitHub App CI

on:
  workflow_dispatch:

jobs:
  run-app:
    runs-on: ubuntu-latest

    # env:
    #   APP_ID: ${{ secrets.APP_ID }}
    #   PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    #   WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
    #   CLIENT_ID: ${{ secrets.CLIENT_ID }}
    #   CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: githubapp

      - name: Create private key file
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > githubapp/private-key.pem
          chmod 600 githubapp/private-key.pem

      - name: Run the GitHub App
        run: npx probot run .
        working-directory: githubapp
